name: Build

on: [push]

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]

    steps:
      - uses: actions/checkout@v1
      - name: Install Rust
        uses: hecrj/setup-rust-action@v1
      - name: Build
        run: cargo  build --verbose
      - name: Run tests
        run: cargo test --verbose
      - name: Code coverage
        uses: codecov/codecov-action@v1
        with:
          file: ./coverage.xml # optional
          fail_ci_if_error: true # optional (default = false)